image: stamus/stamus-docker-qa:chromium
npm:
  image: node:8.9.4
  stage: build
  artifacts:
    expire_in: 1 day
    paths:
    - rules/static/dist
    - rules/static/bundles
    - rules/static/webpack-stats.prod.json
  before_script:
  - echo "skip"
  script:
  - npm install
  - npm install -g webpack@3.11
  - webpack
  - cd hunt
  - npm install
  - npm run build
  - node node_modules/eslint/bin/eslint.js -c .eslintrc .

test-static:
  stage: test
  script:
  - /home/admin/venv/bin/pylint --load-plugins pylint_django -E -d unexpected-keyword-arg,no-member,access-member-before-definition,no-name-in-module,import-error,imported-auth-user */*.py
  - PYTHONIOENCODING="UTF-8" ./tests/check_non_ascii_chars.py

eslint_check:
  image: node:8.9.4
  stage: custom
  when: manual
  before_script:
  - echo "skip"
  script:
  - cd hunt
  - npm install
  - cd ..
  - python tests/eslint_check.py $(find hunt -name \*.js |grep -v /node_modules/)

test-dlint:
    image: python
    before_script:
        - python -m pip install dlint
    script:
        - python -m flake8 --select=DUO rules
        - python -m flake8 --select=DUO suricata
        - python -m flake8 --ignore=E501,E722,W504 --exclude=rules/migrations,rules/south_migrations,tests/docker/,accounts/south_migrations,suricata/south_migrations,suricata/migrations rules suricata accounts scirius
